accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"


urlpatterns = [
    path('', views.HomePageView.as_view(), name= 'home'),
    path('signup/',views.register_user, name = 'signup'),
    path('login/', views.login_user, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('profile/', views.profile_view, name = 'profile'),
    path('aboutus/', views.AboutUsPageView.as_view(), name= 'aboutus'),
    path('contactus/', views.ContactUsPageView.as_view(), name= 'contactus'),
    path('profile/update/', views.update_user_profile, name= 'update_user_profile'),
    path('profile/update/phone', views.update_user_profile_phonenumber, name= 'update_user_profile_phonenumber'),
    path('profile/myad/', views.my_ads_view, name = 'myads'),
    path('profile/myad/editad/<str:slug>', views.edit_product, name = 'editad'),
  

]

product/urls.py
from django.urls import path
from .views import product_detail_view, product_list_view, postad,product_list_view_elec,product_list_view_jobs,product_list_view_others,product_list_view_roomdecor,product_list_view_stationary,product_list_view_vehicles
from django.conf import settings
from django.conf.urls.static import static

app_name="product"

urlpatterns = [
    path("", product_list_view, name = 'home'),
    path("electonics/",product_list_view_elec, name = 'electronics'),
    path("jobs/",product_list_view_jobs, name = 'jobs'),
    path("vehicles/",product_list_view_vehicles, name = 'vehicles'),
    path("others/",product_list_view_others, name = 'others'),
    path("roomdecor/",product_list_view_roomdecor, name = 'roomdecor'),
    path("stationary/",product_list_view_stationary, name = 'stationary'),
    path("postad/",postad, name = 'postad'),
    path("<str:slug>/",product_detail_view, name = 'product_detail_view'),
]
static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("product/", include("product.urls")),
    path("accounts/", include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product/forms.py
from django import forms
from . models import Product

class AddProductInfoForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=['title','description','image','price','category']

    title =forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Title','class': 'border w-100 p-2 bg-white text-capitalize'}))
    description=forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Describe Your Product','class':'border p-3 w-100'}))
    price = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder':'Price','class': 'border-0 py-2 w-100 price'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file d-none'}))
    # category = forms.ChoiceField(widget=forms.TextInput(attrs={'class': 'w-100'}))









        #         title =forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username','class': 'border w-100 p-2 bg-white text-capitalize'}))
        # description=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Describe Your Product','class':'border p-3 w-100'}))
        # price = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder':'Price','class': 'border-0 py-2 w-100 price'}))
        # # image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file d-none'}))
        # image = forms.ImageField()

templates/edit_product.html
<form method = "POST">{% csrf_token %}
{{form.as_p}}
<button type = "submit">submit</button>
</form>

templates/home.html
{% extends "base.html" %}
{% block content %}
<section class="section-sm">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<div class="category-sidebar">
					<div class="widget category-list">
	<h4 class="widget-header">All Category</h4>
	<ul class="category-list">
		<li><a href="{% url 'product:electronics'%}">Electronics </a></li>
		<li><a href="{% url 'product:stationary'%}">Stationary </a></li>
		<li><a href="{% url 'product:vehicles'%}">Vehicles </a></li>
		<li><a href="{% url 'product:jobs' %}">Jobs </a></li>
        <li><a href="{% url 'product:roomdecor' %}">Room Decor</a></li>
        <li><a href="{%url 'product:others'%}">Others</a></li>
	</ul>
</div>

<div class="widget category-list">
	<h4 class="widget-header">College</h4>
	<ul class="category-list">
		<li><a href="">NIT KKR </a></li>
	</ul>
</div>

				</div>
			</div>
			<div class="col-md-9">
				<div class="category-search-filter">
					<div class="row">
						<div class="col-md-6">
							<strong>Sort By</strong>
							<select>
								<option>Most Recent</option>
								<option value="1">Most Popular</option>
								<option value="2">Lowest Price</option>
								<option value="4">Highest Price</option>
							</select>
						</div>
						<div class="col-md-6">
							{% comment %} <div class="view">
								<strong>Views</strong>
								<ul class="list-inline view-switcher">
									<li class="list-inline-item">
										<a href="#" onclick="event.preventDefault();" class="text-info"><i class="fa fa-th-large"></i></a>
									</li>
									<li class="list-inline-item">
										<a href="ad-list-view.html"><i class="fa fa-reorder"></i></a>
									</li>
								</ul>
							</div> {% endcomment %}
						</div>
					</div>
				</div>
				<div class="product-grid-list">
					<div class="row mt-30">
						{% for obj in object_list %}
						<div class="col-sm-12 col-lg-4 col-md-6">
							<!-- product card -->
<div class="product-item bg-light">
	<div class="card">
		<div class="thumb-content">
			<!-- <div class="price">$200</div> -->
			<a href="{%url 'product:product_detail_view' obj.slug %}">
				<img class="card-img-top img-fluid" src="{{ obj.image.url }}" alt="Card image cap" href = "{%url 'product:product_detail_view' obj.slug %}">
			</a>
		</div>
		<div class="card-body">
		    <h4 class="card-title"><a href="{%url 'product:product_detail_view' obj.slug %}">{{obj.title}}</a></h4>
		    <ul class="list-inline product-meta">
		    	<li class="list-inline-item">
		    		<a href=""><i class="fa fa-folder-open-o"></i>{{obj.category}}</a>
		    	</li>
		    	<li class="list-inline-item">
		    		<a href="#"><i class="fa fa-calendar"></i>{{obj.date}}</a>
		    	</li>
    	    	<li class="list-inline-item">
		    		<a href="#"><i class="fa fa-inr"></i>{{obj.price}}</a>
		    	</li>
		    </ul>
		    {% comment %} <p class="card-text">{{obj.description}}</p> {% endcomment %}
		    {% comment %} <div class="product-ratings">
		    	<ul class="list-inline">
		    		<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
		    		<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
		    		<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
		    		<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
		    		<li class="list-inline-item"><i class="fa fa-star"></i></li>
		    	</ul>
		    </div> {% endcomment %}
		</div>
	</div>
</div>



						</div>
	{% endfor %} 					
					</div>
				</div>
				<div class="pagination justify-content-center">
					<nav aria-label="Page navigation example">
						<ul class="pagination">
							<li class="page-item">
								<a class="page-link" href="#" aria-label="Previous">
									<span aria-hidden="true">&laquo;</span>
									<span class="sr-only">Previous</span>
								</a>
							</li>
							<li class="page-item active"  ><a class="page-link" href="#">1</a></li>
							<li class="page-item "><a class="page-link" href="#">2</a></li>
							<li class="page-item"><a class="page-link" href="#">3</a></li>
							<li class="page-item">
								<a class="page-link" href="#" aria-label="Next">
									<span aria-hidden="true">&raquo;</span>
									<span class="sr-only">Next</span>
								</a>
							</li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

templates/my_ads.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<section class="dashboard section">
  <!-- Container Start -->
  <div class="container">
    <!-- Row Start -->
    <div class="row">
      <div class="col-md-10 offset-md-1 col-lg-4 offset-lg-0">
        <div class="sidebar">
          <!-- User Widget -->
          <div class="widget user-dashboard-profile">
            <!-- User Image -->
            <div class="profile-thumb">
              <img src="{% static 'images/user.png'%}" alt="" class="rounded-circle">
            </div>
            <!-- User Name -->
            <h5 class="text-center">{{request.user.first_name}} {{request.user.last_name}}</h5>
            <p>joined {{request.user.date}}</p>
            <a href="{% url 'accounts:update_user_profile'%}" class="btn btn-main-sm">Edit Profile</a>
          </div>
          <!-- Dashboard Links -->
           <div class="widget user-dashboard-menu">
                      <ul>  
                      <li  ><a href="{% url 'accounts:update_user_profile'%}"><i class="fa fa-user"></i>Edit Profile</a></li>
                            <li class="active"><a href="{% url 'accounts:myads'%}"><i class="fa fa-bookmark-o"></i> My Ads</a></li>
                            <li><a href=""data-toggle="modal" data-target="#logoutaccount"><i class="fa fa-cog"></i> Logout</a></li>
                            <li><a href="" data-toggle="modal" data-target="#deleteaccount"><i class="fa fa-power-off"></i>Delete
                  Account</a></li>
                    </ul>
          </div>

          <!-- delete-account modal -->
          						  <!-- delete account popup modal start-->
                <!-- Modal -->
                <div class="modal fade" id="deleteaccount" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                  aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header border-bottom-0">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body text-center">
                        <img src="images/account/Account1.png" class="img-fluid mb-2" alt="">
                        <h6 class="py-2">Are you sure you want to delete your account?</h6>
                        <p>Do you really want to delete these records? This process cannot be undone.</p>
                        <textarea name="message" id="" cols="40" rows="4" class="w-100 rounded"></textarea>
                      </div>
                      <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-danger">Delete</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- delete account popup modal end-->
                <div class="modal fade" id="logoutaccount" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                  aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header border-bottom-0">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body text-center">
                        <img src="images/account/Account1.png" class="img-fluid mb-2" alt="">
                        <h6 class="py-2">Are you sure you want to Logout your account?</h6>
                        <p>Keep smiling and selling products</p>
                      </div>
                      <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                        <a href = "{% url 'accounts:logout'%}"><button type="button" class="btn btn-danger">Logout</button></a>
                      </div>
                    </div>
                  </div>
                </div>
          <!-- delete-account modal -->

        </div>
      </div>
      <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-0">
        <!-- Recently Favorited -->
        <div class="widget dashboard-container my-adslist">
          <h3 class="widget-header">My Ads</h3>
          <table class="table table-responsive product-dashboard-table">
            <thead>
              <tr>
                <th>Image</th>
                <th>Product Title</th>
                <th class="text-center">Category</th>
                <th class="text-center">Action</th>
              </tr>
            </thead>
            <tbody>
            {% for product in query_set %}
            
          
              <tr>

                <td class="product-thumb">
                  <img width="80px" height="auto" src="{{ product.image.url }}" alt="image description"></td>
                <td class="product-details">
                  <h3 class="title">{{product.title}}</h3>
                  <span><strong>Posted on: </strong><time>{{product.date}}</time> </span>
                  <span  class="fa fa-inr"><strong>Price: </strong>{{product.price}} </span>
                  <span class="status active"><strong>Status</strong>Active</span>
                </td>
                <td class="product-category"><span class="categories">{{product.category}}</span></td>
                <td class="action" data-title="Action">
                  <div class="">
                    <ul class="list-inline justify-content-center">
                      <li class="list-inline-item">
                        <a data-toggle="tooltip" data-placement="top" title="view" class="view" href="{% url 'product:product_detail_view' product.slug %}">
                          <i class="fa fa-eye"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a class="edit" data-toggle="tooltip" data-placement="top" title="Edit" href="{% url 'accounts:editad' product.slug %}">
                          <i class="fa fa-pencil"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a class="delete" data-toggle="tooltip" data-placement="top" title="Delete" href="">
                          <i class="fa fa-trash"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
              <tr>

                {% endfor %}
            </tbody>
          </table>

        </div>
        <h3>No ads to display<h3>
        <!-- pagination -->
        <div class="pagination justify-content-center">
					<nav aria-label="Page navigation example">
						<ul class="pagination">
							<li class="page-item">
								<a class="page-link" href="#" aria-label="Previous">
									<span aria-hidden="true">&laquo;</span>
									<span class="sr-only">Previous</span>
								</a>
							</li>
							<li class="page-item active"><a class="page-link" href="#">1</a></li>
							<li class="page-item "><a class="page-link" href="#">2</a></li>
							<li class="page-item"><a class="page-link" href="#">3</a></li>
							<li class="page-item">
								<a class="page-link" href="#" aria-label="Next">
									<span aria-hidden="true">&raquo;</span>
									<span class="sr-only">Next</span>
								</a>
							</li>
						</ul>
					</nav>
				</div>
        <!-- pagination -->

      </div>
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</section>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<section class="user-profile section">
	<div class="container">
		<div class="row">
			<div class="col-md-10 offset-md-1 col-lg-3 offset-lg-0">
				<div class="sidebar">
					<!-- User Widget -->
					<div class="widget user">
						<!-- User Image -->
						<div class="image d-flex justify-content-center">
							<img src="{% static 'images/user.png'%}" alt="" class="">
						</div>
						<!-- User Name -->
						<h5 class="text-center">{{user.first_name}} {{user.last_name}}</h5>
					</div>
					<!-- Dashboard Links -->
                    <div class="widget user-dashboard-menu">
                      <ul>  
                    <li  ><a href="{% url 'accounts:update_user_profile'%}"><i class="fa fa-user"></i>Edit Profile </a></li>
                            <li class=""><a href="{% url 'accounts:myads'%}"><i class="fa fa-bookmark-o"></i> My Ads</a></li>
                            <li><a href="" data-toggle="modal" data-target="#logoutaccount"><i class="fa fa-cog"></i> Logout</a></li>
                            <li><a href="" data-toggle="modal" data-target="#deleteaccount"><i class="fa fa-power-off"></i>Delete
                  Account</a></li>
                    </ul>
          </div>
				</div>
                <div class="modal fade" id="deleteaccount" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                  aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header border-bottom-0">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body text-center">
                        <img src="images/account/Account1.png" class="img-fluid mb-2" alt="">
                        <h6 class="py-2">Are you sure you want to delete your account?</h6>
                        <p>Do you really want to delete these records? This process cannot be undone.</p>
                        <textarea name="message" id="" cols="40" rows="4" class="w-100 rounded"></textarea>
                      </div>
                      <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-danger">Delete</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- delete account popup modal end-->
                <div class="modal fade" id="logoutaccount" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                  aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header border-bottom-0">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body text-center">
                        <img src="images/account/Account1.png" class="img-fluid mb-2" alt="">
                        <h6 class="py-2">Are you sure you want to Logout your account?</h6>
                        <p>Keep smiling and selling products</p>
                      </div>
                      <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'accounts:logout'%}"><button type="button" class="btn btn-danger">Logout</button></a>
                      </div>
                    </div>
                  </div>
                </div>
			</div>
			<div class="col-md-10 offset-md-1 col-lg-9 offset-lg-0">
				<!-- Edit Profile Welcome Text -->
				<div class="widget welcome-message">
					<h2>View Profile</h2>
					<p>Here you can view your profile. You can also edit it in the edit section.</p>
				</div>
				<!-- Edit Personal Info -->
				<div class="row">

						
    					<div class="tab-pane" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
								<h3 class="tab-title">User Details</h3>
								<table class="table table-bordered product-table">
									<tbody>
										<tr>
											<td>Name</td>
											<td>{{request.user.first_name}} {{request.user.last_name}}</td>
										</tr>
										<tr>
											<td>Email</td>
											<td>{{request.user.email}}</td>
										</tr>
										<tr>
											<td>Phone</td>
											<td>{{request.user.phone}}</td>
										</tr>
										<tr>
											<td>Member Since</td>
											<td>{{request.user.date}}</td>
										</tr>
									</tbody>
								</table>
							</div> 
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock content %}

templates/update.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<section class="user-profile section">
	<div class="container">
		<div class="row">
			<div class="col-md-10 offset-md-1 col-lg-3 offset-lg-0">
				<div class="sidebar">
					<!-- User Widget -->
					<div class="widget user">
						<!-- User Image -->
						<div class="image d-flex justify-content-center">
							<img src="{% static 'images/user.png'%}" alt="" class="">
						</div>
						<!-- User Name -->
						<h5 class="text-center">{{user.first_name}} {{user.last_name}}</h5>
					</div>
					<!-- Dashboard Links -->
                    <div class="widget user-dashboard-menu">
                         <ul>  
                    <li  ><a href="{% url 'accounts:update_user_profile'%}"><i class="fa fa-user active"></i>Edit Profile </a></li>
                            <li ><a href="{% url 'accounts:myads'%}"><i class="fa fa-bookmark-o"></i> My Ads</a></li>
                            <li><a href="" data-toggle="modal" data-target="#logoutaccount"><i class="fa fa-cog"></i> Logout</a></li>
                            <li><a href="" data-toggle="modal" data-target="#deleteaccount"><i class="fa fa-power-off"></i>Delete
                  Account</a></li>
                    </ul>
          </div>
				</div>

                <div class="modal fade" id="deleteaccount" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                  aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header border-bottom-0">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body text-center">
                        <img src="images/account/Account1.png" class="img-fluid mb-2" alt="">
                        <h6 class="py-2">Are you sure you want to delete your account?</h6>
                        <p>Do you really want to delete these records? This process cannot be undone.</p>
                        <textarea name="message" id="" cols="40" rows="4" class="w-100 rounded"></textarea>
                      </div>
                      <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-danger">Delete</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- delete account popup modal end-->
                <div class="modal fade" id="logoutaccount" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                  aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header border-bottom-0">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body text-center">
                        <img src="images/account/Account1.png" class="img-fluid mb-2" alt="">
                        <h6 class="py-2">Are you sure you want to Logout your account?</h6>
                        <p>Keep smiling and selling products</p>
                      </div>
                      <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'accounts:logout'%}"><button type="button" class="btn btn-danger">Logout</button></a>
                      </div>
                    </div>
                  </div>
                </div>
			</div>
			<div class="col-md-10 offset-md-1 col-lg-9 offset-lg-0">
				<!-- Edit Profile Welcome Text -->
				<div class="widget welcome-message">
					<h2>Edit profile</h2>
					<p>Here you can edit your details. Give accurate details for better selling</p>
				</div>
{% for message in messages %}

                    <div class="alert alert-danger">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}

                    </div>
            {% endfor %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
				<div class="row">
					<div class="col-lg-6 col-md-6">
						<div class="widget personal-info">
							<h3 class="widget-header user">Edit Personal Information</h3>
							<form method = "POST">{% csrf_token %}
								<!-- First Name -->
								<div class="form-group">
									<label for="first-name">First Name</label>
									{{form.first_name}}
								</div>
								<!-- Last Name -->
								<div class="form-group">
									<label for="last-name">Last Name</label>
									{{form.last_name}}
								</div>
																<div class="form-group">
									<label for="last-name">Last Name</label>
									{{form.phone}}
								</div>
								<!-- File chooser -->
								{% comment %} <div class="form-group choose-file d-inline-flex">
									<i class="fa fa-user text-center px-3"></i>
									<input type="file" class="form-control-file mt-2 pt-1" id="input-file">
								 </div> {% endcomment %}
								{% comment %} <!-- Comunity Name -->
								<div class="form-group">
									<label for="comunity-name">Comunity Name</label>
									<input type="text" class="form-control" id="comunity-name">
								</div>
								<!-- Checkbox -->
								<div class="form-check">
								  <label class="form-check-label" for="hide-profile">
									<input class="form-check-input mt-1" type="checkbox" value="" id="hide-profile">
									Hide Profile from Public/Comunity
								  </label>
								</div> {% endcomment %}
								<!-- Submit button -->

								<button type="submit" name="submitname" class="btn btn-transparent">Save My Changes</button>
							</form>
						</div>
					</div>
					<div class="col-lg-6 col-md-6">
						<!-- Change Password -->
					<div class="widget change-password">
						<h3 class="widget-header user">Edit Password</h3>
						<form action="#">
							<!-- Current Password -->
							<div class="form-group">
								<label for="current-password">Current Password</label>
								<input type="password" class="form-control" id="current-password">
							</div>
							<!-- New Password -->
							<div class="form-group">
								<label for="new-password">New Password</label>
								<input type="password" class="form-control" id="new-password">
							</div>
							<!-- Confirm New Password -->
							<div class="form-group">
								<label for="confirm-password">Confirm New Password</label>
								<input type="password" class="form-control" id="confirm-password">
							</div>
							<!-- Submit Button -->
							<button class="btn btn-transparent">Change Password</button>
						</form>
					</div>
					</div>
					{% comment %} 
					<div class="col-lg-6 col-md-6">
						<!-- Change Email Address -->
					<div class="widget change-email mb-0">
						<h3 class="widget-header user">Edit Email Address</h3>
						<form action="#">
							<!-- Current Password -->
							<div class="form-group">
								<label for="current-email">Current Email</label>
								<input type="email" class="form-control" id="current-email">
							</div>
							<!-- New email -->
							<div class="form-group">
								<label for="new-email">New email</label>
								<input type="email" class="form-control" id="new-email">
							</div>
							<!-- Submit Button -->
							<button class="btn btn-transparent">Change email</button>
						</form>
					</div>
					</div>
                    <div class="col-lg-6 col-md-6">
						<!-- Change Password -->
					<div class="widget change-password">
						<h3 class="widget-header user">Edit Mobile No.</h3>
						<form action="#">{% csrf_token %}
						{{form.as_p}}
							{% comment %} <!-- Current Password -->
							<div class="form-group">
								<label for="current-password">Current Mobile No.</label>
								<input type="number" class="form-control" id="current-password">
								{{request.user.}}
							</div>
							<!-- New Password -->
							<div class="form-group">
								<label for="new-password">New Mobile No.</label>
								<input type="number" class="form-control" id="new-password">
							</div>
							<!-- Submit Button -->
							<button type ="submit" class="btn btn-transparent" name="submitphone">Change Mobile No.</button> 
						</form>
					</div>
					</div> {% endcomment %}
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock content %}